[dbtools]
dbtools.ambudot.work ansible_host=192.168.1.160

[mariadb]
mariadb.ambudot.work ansible_host=192.168.1.161

[postgresql]
postgresql.ambudot.work ansible_host=192.168.1.162

# VM GitLab — décommente quand son IP .203 sera posée
# [gitlab]
# gitlab.ambudot.work ansible_host=192.168.1.203 ansible_user=ambudot ansible_become=true

[databases:children]
mariadb
postgresql
